package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class AdminFtnsController {
	@FXML
	private Button managepassinfobtn;
	@FXML
	private Button managernfinfobtn;
	@FXML
	private Button checkbkctrbtn;
	
	@FXML
    private Button baackButton;


	// Event Listener on Button[#managepassinfobtn].onAction
	@FXML
	public void ManagePassengerBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) managepassinfobtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MngPssngrInfo.fxml"));
		primaryStage.setTitle("Manage Passenger Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#managernfinfobtn].onAction
	@FXML
	public void MngRandFBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) managernfinfobtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MngRouteInfo.fxml"));
		primaryStage.setTitle("Manage Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#checkbkctrbtn].onAction
	@FXML
	public void ChkBookingCtrBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) checkbkctrbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("CheckBookingCtr.fxml"));
		primaryStage.setTitle("Check Booking Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	 @FXML
	    void backToLoginPage(ActionEvent event) throws IOException {
		 Stage stage = (Stage) baackButton.getScene().getWindow();
			stage.close();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("Login.fxml"));
			primaryStage.setTitle("Login Page");
			primaryStage.setScene(new Scene(root));
			primaryStage.show();
	    }
}
