package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

import java.io.IOException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class CashPaymentController {
	@FXML
	private Button cashpaymentconfirmbtn;
	@FXML
	private TextField paymentamt;
	@FXML
	private Button BBButton;
	
	Metro controller = new Metro();

	// Event Listener on Button[#cashpaymentconfirmbtn].onAction
	@FXML
	public void MakeCashPaymentBtn(ActionEvent event) {
		// TODO Autogenerated
		controller.getInstance().makePayment(Integer.parseInt(paymentamt.getText()));
		infoBox("Payment paid sucessfully!!",null,"Successful");
	}
   private void infoBox(String info, String header, String title) {
		
    	Alert alert = new Alert(AlertType.CONFIRMATION);
    	 alert.setContentText(info);
         alert.setTitle(title);
         alert.setHeaderText(header);
         alert.showAndWait();
	}
	// Event Listener on Button[#BBButton].onAction
	@FXML
	public void gotoMakePayment(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MakePayment.fxml"));
		primaryStage.setTitle("Make Payment");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
}
