package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class CheckBookingCtrController {
    @FXML
    private Button BBButton;
	@FXML
	private Button checkctrbtn;
	@FXML
	private TextField getroute;
	
	 @FXML
	    private Label RouteCounter;

	
	Metro controller = new Metro();

	// Event Listener on Button[#checkctrbtn].onAction
	@FXML
	public void CheckCtr(ActionEvent event) throws ClassNotFoundException, SQLException {
		// TODO Autogenerated
		String Route = getroute.getText();
		System.out.println(Route);
		int the_totalprice= Metro.getInstance().checkBookingCounter(getroute.getText());
		System.out.println(the_totalprice);
		String str = Integer.toString(the_totalprice);
		
		RouteCounter.setText(str);
	//.controller.getInstance().checkBookingCounter(getroute.getText());
	}
	
	@FXML
    void gotoadminFtns(ActionEvent event) throws IOException {
		 Stage stage = (Stage) BBButton.getScene().getWindow();
			stage.close();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("AdminFtns.fxml"));
			primaryStage.setTitle("Mng Passenger Page");
			primaryStage.setScene(new Scene(root));
			primaryStage.show();
    }
}
