package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class DeleteRouteController {
	@FXML
	private Button deleteRbtn;
	@FXML
	private TextField getpsngrid;
    
	  @FXML
	    private Button BBButton;
	// Event Listener on Button[#deleteRbtn].onAction
	  Metro controller = new Metro();
	@FXML
	public void DeleteRoute(ActionEvent event) throws ClassNotFoundException, SQLException {
		
		// TODO Autogenerated'
		boolean val = controller.getInstance().verifyRoute(getpsngrid.getText());
		if(val == true)
		{controller.getInstance().deleteRoute(getpsngrid.getText());
	     infoBox("Route deleted sucessfully!!",null,"Successful");
	}
	}
   private void infoBox(String info, String header, String title) {
		
    	Alert alert = new Alert(AlertType.CONFIRMATION);
    	 alert.setContentText(info);
         alert.setTitle(title);
         alert.setHeaderText(header);
         alert.showAndWait();
		
	}
	
	

    @FXML
    void gotoMngRoute(ActionEvent event) throws IOException {
    	Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MngRouteInfo.fxml"));
		primaryStage.setTitle("Mng Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
    }

}
