package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;


import javafx.scene.control.Label;
import javafx.stage.Stage;


import javafx.scene.control.TextField;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class DisplayFaresController implements Initializable {
	@FXML
	private Button dispfarebtn;
	@FXML
	private TextField routename;
	@FXML
    private Button BBButton;
	@FXML
	private Label getfair;
	public String Route;
	
	
	  @FXML
	    private Label FareDisplay;

	// Event Listener on Button[#dispfarebtn].onAction
	private void refreshTable() throws SQLException, ClassNotFoundException
    {
		Route = routename.getText();
		//getfaresss.setText("0");
    	
    	
    	
    }
	public void initialize(URL location, ResourceBundle resources) {
		 

    	
		//loaddata();
		
		try {
			try {
				refreshTable();
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}

//
	}
	@FXML
	public void DisplayFare(ActionEvent event) throws ClassNotFoundException, SQLException {
		// TODO Autogenerated
		Route = routename.getText();
		System.out.println(Route);
		double the_totalprice= Metro.getInstance().GetFare(Route);
		System.out.println(the_totalprice);
		String str = Double.toString(the_totalprice);
		
		getfair.setText(str);
	}
	
	
	
	@FXML
    void gotoUser(ActionEvent event)throws IOException {
		Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("PassengerFtns.fxml"));
		primaryStage.setTitle("Passenger Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
    }
}
