package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class MakePaymentController {
	@FXML
	private Button cardpaymentbtn;
	@FXML
	private Button cashpaymentbtn;
	 @FXML
	    private Button BBButton;

	// Event Listener on Button[#cardpaymentbtn].onAction
	@FXML
	public void CardBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) cardpaymentbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("AmountPayment.fxml"));
		primaryStage.setTitle("Card Payment");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#cashpaymentbtn].onAction
	@FXML
	public void CashBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) cashpaymentbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("CashPayment.fxml"));
		primaryStage.setTitle("Cash Payment");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	
	@FXML
    void gotoUser(ActionEvent event) throws IOException {
		Stage stage = (Stage) cardpaymentbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("BookTicket.fxml"));
		primaryStage.setTitle("Make Payment");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
    }
}
