package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class MngRouteInfoController {
	@FXML
    private Button BBButton;
	@FXML
	private Button createrotuebtn;
	@FXML
	private Button searchroutebtn;
	@FXML
	private Button updateroutebtn;
	@FXML
	private Button deleteroutebtn;

	// Event Listener on Button[#createrotuebtn].onAction
	@FXML
	public void CreateBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) createrotuebtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("CreateRoute.fxml"));
		primaryStage.setTitle("Create Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#searchroutebtn].onAction
	@FXML
	public void SearchBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) searchroutebtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("SearchRoute.fxml"));
		primaryStage.setTitle("Search Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();

	}
	// Event Listener on Button[#updateroutebtn].onAction
	@FXML
	public void UpdateBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) updateroutebtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("UpdateRoute.fxml"));
		primaryStage.setTitle("Update Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();

	}
	// Event Listener on Button[#deleteroutebtn].onAction
	@FXML
	public void DeleteBtn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) deleteroutebtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("DeleteRoute.fxml"));
		primaryStage.setTitle("Delete Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
		
	}
	
	@FXML
    void gotoadminFtns(ActionEvent event) throws IOException {
		 Stage stage = (Stage) BBButton.getScene().getWindow();
			stage.close();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("AdminFtns.fxml"));
			primaryStage.setTitle("Mng Passenger Page");
			primaryStage.setScene(new Scene(root));
			primaryStage.show();
    }

}