package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class PassengerFtnsController {
	@FXML
	private Button makepaymentbtn;
	@FXML
	private Button regcomplaintbtn;
	@FXML
	private Button dispfaresbtn;
	@FXML
    private Button BBButton;

	// Event Listener on Button[#makepaymentbtn].onAction
	@FXML
	public void Paymentftn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) makepaymentbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("BookTicket.fxml"));
		primaryStage.setTitle("Book Ticket Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#regcomplaintbtn].onAction
	@FXML
	public void Registerftn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) regcomplaintbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("RegisterComplaint.fxml"));
		primaryStage.setTitle("Complaint Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	// Event Listener on Button[#dispfaresbtn].onAction
	@FXML
	public void displayftn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) dispfaresbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("DisplayFares.fxml"));
		primaryStage.setTitle("Fare Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
	
	@FXML
    void gotoLogin(ActionEvent event) throws IOException {
		Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("Login.fxml"));
		primaryStage.setTitle("Login Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
    }
}
