package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class RcpFtnsController {
	@FXML
	private Button bookticketbtn;

	// Event Listener on Button[#bookticketbtn].onAction
	@FXML
	public void BookTicket(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) bookticketbtn.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("BookTicket.fxml"));
		primaryStage.setTitle("Book Ticket Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
}
