package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class RegisterComplaintController {
	@FXML
	private Button registerbtn;
	@FXML
	private TextField complaintcontent;
	@FXML
    private Button BBButton;
	
	Metro controller = new Metro();

	// Event Listener on Button[#registerbtn].onAction
	@FXML
	public void RegisterComplaint(ActionEvent event) throws ClassNotFoundException, SQLException {
		// TODO Autogenerated
		controller.getInstance().registerComplaint(complaintcontent.getText());
		infoBox("Complaint registered sucessfully!!",null,"Successful");
	}
	   private void infoBox(String info, String header, String title) {
			
	    	Alert alert = new Alert(AlertType.CONFIRMATION);
	    	 alert.setContentText(info);
	         alert.setTitle(title);
	         alert.setHeaderText(header);
	         alert.showAndWait();
	}
	
	@FXML
    void gotoUser(ActionEvent event) throws IOException {
		Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		//authenticate receptionist
		
		Parent root = FXMLLoader.load(getClass().getResource("PassengerFtns.fxml"));
		primaryStage.setTitle("Passenger Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
    }
}
