package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class SearchPassengerController {
	@FXML
	private Button searchbtn;
	@FXML
	private TextField getpsngrid;
	@FXML
	private Button BBButton;
	Metro control = new Metro();

	// Event Listener on Button[#searchbtn].onAction
	@FXML
	public void SearchPssngrftn(ActionEvent event) throws NumberFormatException, ClassNotFoundException, SQLException {
		// TODO Autogenerated
		control.getInstance().searchPassenger(Integer.parseInt(getpsngrid.getText()));
	}
	// Event Listener on Button[#BBButton].onAction
	@FXML
	public void gotoMNGPsngr(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MngPssngrInfo.fxml"));
		primaryStage.setTitle("Mng Passenger Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
}
