package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class SearchRouteController {
	@FXML
	private Button SearchRbtn;
	@FXML
	private TextField getroute;
	 @FXML
	    private Button BBButton;

	 Metro controller = new Metro();
	// Event Listener on Button[#SearchRbtn].onAction
	@FXML
	public void SearchBtn(ActionEvent event) throws ClassNotFoundException, SQLException {
		// TODO Autogenerated
		controller.getInstance().searchRoute(getroute.getText());
	}
	@FXML
    void gotoMngRoute(ActionEvent event) throws IOException {
    	Stage stage = (Stage) BBButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("MngRouteInfo.fxml"));
		primaryStage.setTitle("Mng Route Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
}
