package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;

import BusinessLogic.Metro;
import javafx.event.ActionEvent;

public class UpdateRouteController {
	@FXML
	private Button updateRbtn;
	@FXML
	private TextField routename;
	@FXML
	private TextField routefare;
	@FXML
	private TextField routetime;
	@FXML
	private Button BBButton;
	@FXML
	private TextField routeseats;

	 Metro controller = new Metro();
	// Event Listener on Button[#updateRbtn].onAction
	@FXML
	public void UpdateRoute(ActionEvent event) throws ClassNotFoundException, SQLException {
		// TODO Autogenerated
		boolean val = controller.getInstance().verifyRoute(routename.getText());
		if(val == true)
		{
			 controller.getInstance().updateRoute(routename.getText(),Integer.parseInt(routefare.getText()) , routetime.getText(), Integer.parseInt(routeseats.getText()));
			 infoBox("Route Created sucessfully!!",null,"Successful");		
	    }
	}
		 private void infoBox(String info, String header, String title) {
				
		    	Alert alert = new Alert(AlertType.CONFIRMATION);
		    	 alert.setContentText(info);
		         alert.setTitle(title);
		         alert.setHeaderText(header);
		         alert.showAndWait();
	}
	
	// Event Listener on Button[#BBButton].onAction
	@FXML
	public void gotoMngRoute(ActionEvent event) throws IOException {
		// TODO Autogenerated
		 Stage stage = (Stage) BBButton.getScene().getWindow();
			stage.close();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("MngRouteInfo.fxml"));
			primaryStage.setTitle("Mng Route Page");
			primaryStage.setScene(new Scene(root));
			primaryStage.show();
	}
}
