package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class WelcomeSceneController {
	@FXML
	private Button LoginButton;

	// Event Listener on Button[#LoginButton].onAction
	@FXML
	public void LoginClick(ActionEvent event) throws IOException
	{
		// TODO Autogenerated
		Stage stage = (Stage) LoginButton.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("Login.fxml"));
		primaryStage.setTitle("Login Page");
		primaryStage.setScene(new Scene(root));
		primaryStage.show();
	}
}
